"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTypeOfPropertyOfTypeImpl = exports.isUndefinedTypeImpl = exports.isTupleTypeImpl = exports.isStringTypeImpl = exports.isReadonlyArrayTypeImpl = exports.isNumberTypeImpl = exports.isNullTypeImpl = exports.isBooleanTypeImpl = exports.isArrayTypeImpl = exports.isAnyTypeImpl = exports.getElementTypeOfArrayTypeImpl = void 0;
;
var getElementTypeOfArrayTypeImpl = function (checker, type) { return checker.getElementTypeOfArrayType(type) || null; };
exports.getElementTypeOfArrayTypeImpl = getElementTypeOfArrayTypeImpl;
var isAnyTypeImpl = function (checker, type) { return checker.getAnyType() == type; };
exports.isAnyTypeImpl = isAnyTypeImpl;
var isArrayTypeImpl = function (checker, type) { return checker.isArrayType(type); };
exports.isArrayTypeImpl = isArrayTypeImpl;
var isBooleanTypeImpl = function (checker, type) { return checker.getBooleanType() == type; };
exports.isBooleanTypeImpl = isBooleanTypeImpl;
var isNullTypeImpl = function (checker, type) { return checker.getNullType() == type; };
exports.isNullTypeImpl = isNullTypeImpl;
var isNumberTypeImpl = function (checker, type) { return checker.getNumberType() == type; };
exports.isNumberTypeImpl = isNumberTypeImpl;
var isReadonlyArrayTypeImpl = function (checker, type) { return checker.isReadonlyArrayType(type); };
exports.isReadonlyArrayTypeImpl = isReadonlyArrayTypeImpl;
var isStringTypeImpl = function (checker, type) { return checker.getStringType() == type; };
exports.isStringTypeImpl = isStringTypeImpl;
var isTupleTypeImpl = function (checker, type) { return checker.isTupleType(type); };
exports.isTupleTypeImpl = isTupleTypeImpl;
var isUndefinedTypeImpl = function (checker, type) { return checker.getUndefinedType() == type; };
exports.isUndefinedTypeImpl = isUndefinedTypeImpl;
var getTypeOfPropertyOfTypeImpl = function (checker, type, propertyName) { return checker.getTypeOfPropertyOfType(type, propertyName) || null; };
exports.getTypeOfPropertyOfTypeImpl = getTypeOfPropertyOfTypeImpl;
//# sourceMappingURL=Internal.js.map